name: Docker Server Monitor

on:
  push:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes

jobs:
  docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t server-monitor .

      - name: Run Docker container
        run: docker run server-monitor
