name: DevOps Monitoring Pipeline

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  network-monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run network monitor
        run: |
          docker build -t server-monitor .
          docker run server-monitor

  system-monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run system monitor
        run: |
          docker build -t system-monitor .
          docker run system-monitor

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: system-monitor-logs
          path: system_monitor.log
