name: DevOps Monitoring Pipeline

on:
  push:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes

jobs:

  network-monitor:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and run network monitor
        run: |
          docker build -t server-monitor . || true
          docker run \
            -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN \
            -e CHAT_ID=$CHAT_ID \
            server-monitor || true


  system-monitor:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and run system monitor
        run: |
          docker build -t system-monitor . || true
          docker run \
            -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN \
            -e CHAT_ID=$CHAT_ID \
            system-monitor || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: system-monitor-logs
          path: system_monitor.log
